### ISSUE TITLE
How to specify CorelDRAW to import text as curves?

### ISSUE THREAD

**Issue by ethanlu2** [InteractiveComputerGraphics/Latex4CorelDRAW#2]
Hi Bender, much appreciate ur work. But I'm wondering how to specify CorelDRAW to import PS file's text as curves? LaTex uses afm(or pfb) font when generating PS file, but CorelDraw can't use these fonts, so it replaces them with default font for the generated equations.  I tried convert pfb or afm font into ttf font, but it did not come out well even installing via font manager. 
So, is it possible to specify CorelDRAW to import text as curves for generated PS file in C# program? I found no item about this setting in ImportFilter class and StructImportOptions class. Please help!

**Comment by janbender** [comment]
I didn't find an option to do this in the C# code. However, if you import a PS file manually as curves, CorelDRAW seems to store this option. Afterwards also the PS import in my plugin should import the PS files as curves.

**Comment by mfschumann** [comment]
Hey, I faced the same problem and ended up converting the PS file to PDF with -dNoOutputFonts option to convert the fonts to curves. Then I use the PDF file instead of the PS file for import into Corel. I implemented this workaround into Jan's code and opened a [pull request](https://github.com/InteractiveComputerGraphics/Latex4CorelDRAW/pull/1).

**Comment by janbender** [comment]
Unfortunately this does not solve the problem. In both cases you have to import a PS/PDF file manually as curves and then CorelDraw stores this setting. However, there is no possibility to enforce this in the API.

**Comment by mfschumann** [comment]
Using the -dNoOutputFonts option the intermediate PDF contains only curves, no fonts. So CorelDraw can only import the text as curves.

**Comment by janbender** [comment]
Ok, I will check this.

**Comment by janbender** [comment]
It works. So I merged your pull request.
