### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Gimaevazat** [InteractiveComputerGraphics/Latex4CorelDRAW#7]
Hello, I have some problems.
I downloaded the latest version, rebuilt it in Visual Studio, but when I try to draw a formula, I get an error.
![image](https://user-images.githubusercontent.com/55442406/184990544-728556f5-b407-4ba4-86a9-8319c1ea0ed4.png)
If you help me, I will be very grateful to you.
Full text in Error window:
ssThis is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 22.7) (preloaded format=latex.fmt)
 restricted \write18 enabled.
entering extended mode
(teximport.tex
LaTeX2e <2022-06-01> patch level 5
L3 programming layer <2022-07-04>
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/base\size12.clo))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsmath.sty
For additional information on amsmath, use the `?' option.
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amstext.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsgen.sty))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsbsy.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsopn.sty))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\amsfonts.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\amssymb.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amscls\amsthm.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/mathtools\mathtools.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/tools\calc.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/mathtools\mhsetup.sty))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/cases\cases.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/base\fontenc.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/cyrillic\t2aenc.def
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/base\t2aenc.dfu))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/cyrillic\t2acmr.fd))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/base\inputenc.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/generic/babel\babel.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/generic/babel\txtbabel.def)
*************************************
* Local config file bblopts.cfg used
*
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/arabi\bblopts.cfg)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/babel-english\english.ld
f)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/babel-russian\russianb.l
df))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/generic/babel/locale/ru\babel-
russian.tex)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/generic/babel/locale/en\babel-
english.tex) (C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/bbm\bbm.sty
) (C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/ae\ae.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/base\fontenc.sty))
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/ae\aecompl.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics\color.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\color.cfg)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics-def\dvips.def)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics\dvipsnam.def)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex-dev/graphics\mathcolor.l
tx)) (C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/ae\t1aer.fd)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-dvip
s.def) (teximport.aux
LaTeX Font Warning: Font shape `T2A/aer/m/n' undefined
(Font)              using `T2A/cmr/m/n' instead on input line 5.
) (C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphicx.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphics.sty
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics\trig.sty)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\graphics.cf
g)))
LaTeX Font Warning: Font shape `T2A/ptm/m/n' undefined
(Font)              using `T2A/cmr/m/n' instead on input line 17.
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsa.fd)
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsb.fd)
[1] (teximport.aux
(C:\Users\User\AppData\Local\Programs\MiKTeX\tex/latex/psnfss\t1ptm.fd))
LaTeX Font Warning: Some font shapes were not available, defaults substituted.
 )
Output written on teximport.dvi (1 page, 384 bytes).
Transcript written on teximport.log.
latex: security risk: running with elevated privileges

latex: major issue: So far, you have not checked for MiKTeX updates.

**Comment by janbender** [comment]
This is not a problem of the plugin but the error messages of MiKTeX. This means something is wrong in your tex code. 

You can find the tex file that is used here:
C:\Users\<Your user name>\AppData\Roaming\Latex4CorelDraw\teximport.tex

There is also the template which is used to generate the file: 
C:\Users\<Your user name>\AppData\Roaming\Latex4CorelDraw\LatexTemplate.txt

But it seems that latex complains about this: 
latex: major issue: So far, you have not checked for MiKTeX updates.

**Comment by Gimaevazat** [comment]
Hello. Yes, that was the problem. Thanks for your help and great tool.
